// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3vpqMhaosapQhPtHhMlXa2YnrO1VAsLQ',
    appId: '1:429369073135:web:08d3abb10c5bf1059d6a1a',
    messagingSenderId: '429369073135',
    projectId: 'a24-mobile2-formatif-final',
    authDomain: 'a24-mobile2-formatif-final.firebaseapp.com',
    storageBucket: 'a24-mobile2-formatif-final.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6mdDS41ZqYe0x4PmgIKpeZ9FRfvqqIy0',
    appId: '1:429369073135:android:598f4c0bf033d7ef9d6a1a',
    messagingSenderId: '429369073135',
    projectId: 'a24-mobile2-formatif-final',
    storageBucket: 'a24-mobile2-formatif-final.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9Vqmp4B2f2ju01v6jQW7AFF4z4Cs9muI',
    appId: '1:429369073135:ios:37e0fd3f104041919d6a1a',
    messagingSenderId: '429369073135',
    projectId: 'a24-mobile2-formatif-final',
    storageBucket: 'a24-mobile2-formatif-final.firebasestorage.app',
    iosBundleId: 'com.example.exoFirestoreLazcano',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9Vqmp4B2f2ju01v6jQW7AFF4z4Cs9muI',
    appId: '1:429369073135:ios:37e0fd3f104041919d6a1a',
    messagingSenderId: '429369073135',
    projectId: 'a24-mobile2-formatif-final',
    storageBucket: 'a24-mobile2-formatif-final.firebasestorage.app',
    iosBundleId: 'com.example.exoFirestoreLazcano',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3vpqMhaosapQhPtHhMlXa2YnrO1VAsLQ',
    appId: '1:429369073135:web:3231ca7c7daa71619d6a1a',
    messagingSenderId: '429369073135',
    projectId: 'a24-mobile2-formatif-final',
    authDomain: 'a24-mobile2-formatif-final.firebaseapp.com',
    storageBucket: 'a24-mobile2-formatif-final.firebasestorage.app',
  );

}